### ISSUE TITLE
investigate java tools for downloading large files and validating them (w checksums)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/wasapi-downloader#14]
Is/Are there viable alternative(s) to
- downloading (large) files (background jobs, parallel?) 
- validating file against checksum (sha1, md5)

**Comment by tingulfsen** [comment]
Checksumming with plain Java should be easy - java.security provides the algorithms we need:

https://docs.oracle.com/javase/7/docs/api/java/security/MessageDigest.html

Also see an example:

http://elmurod.net/en/index.php/archives/492

**Comment by tingulfsen** [comment]
The old tool that was used to download WARC files from Archive-It no longer works, but the source code for the download itself is available here:

https://github.com/cul/hrwa_manager/blob/master/src/main/java/edu/columbia/ldpd/hrwa/tasks/DownloadArchiveFilesFromArchivitTask.java

The regular java.io library provides tools that can download files from the Internet:

https://github.com/cul/hrwa_manager/blob/master/src/main/java/edu/columbia/ldpd/hrwa/tasks/DownloadArchiveFilesFromArchivitTask.java#L249-L255

java.nio also provides some potentially more efficient classes for this purpose:

http://stackoverflow.com/questions/921262/how-to-download-and-save-a-file-from-internet-using-java

The HRWA Manager tool referenced above uses multithreading to download files in parallel. This seems to be a fairly common technique in the Java world, as opposed to background processing in the Rails community. There are a number of tools that could be used for background processing in Java though:

* http://projects.spring.io/spring-batch
* http://www.rio-project.org/index.html
* http://www.quartz-scheduler.org/

As usual when working with large files and multithreading, the usual warnings apply (running out of memory while reading files, threads stepping on each other etc.).
