### ISSUE TITLE
validate command line arguments (and settings)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/wasapi-downloader#42]
See #40
- [x] base url is a valid URL
- [ ] account id parses to Integer
- [x] collection id parses to Integer
- [x] crawl id (if provided) parses to integer (crawl ID is AKA job ID)
- [x] crawl start after date parses to ISO8601 UTC format (e.g. "2017-04-01T12:01:05Z", and "2017-04-01" parses to "2017-04-01T23:59:59Z")
- [x] crawl start before ditto

**Comment by jmartin-sul** [comment]
notes from this morning's standup:
* crawl ID is the same as job ID.
* account ID should be an integer, and it should be in the example settings file.
* date may not actually be ISO 8601, e.g. WASAPI endpoint won't accept only a year, but that's valid ISO 8601.

**Comment by jmartin-sul** [comment]
filed #70 as a follow on to address the second point in the above comment.

**Comment by jmartin-sul** [comment]
acceptable date formatting will be determined by some combination of testing and asking for guidance from WASAPI endpoint developers.
