### ISSUE TITLE
review and approve README

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/wasapi-downloader#99]
Nicholas says (per email today):
```
Focusing on the Production Use section, my main question would be: can the downloader in fact be run successfully only supplying a --crawlStartAfter date? Wouldn’t you need to provide a collectionId? Perhaps the assumption is that that’s covered in settings, but I think the more typical use will be to specific the collection as a command-line parameter.
 
Some minor feedback on formatting:
·         Is there a reason why some code blocks are separated by two blank lines from preceding and succeeding content?
·         Code blocks should have consistent indentation.
```

**Comment by ndushay** [comment]
Also:

- explain each of the settings in the sample config/settings.properties
- explain each of the command line settings, and that command line overrides config/settings.properties

Organize:
- "installation" first, then
- "usage", then
- "development"

**Comment by cmharlow** [comment]
https://github.com/sul-dlss/wasapi-downloader/blob/master/README.md#configuration should indicate that for the settings file to be read, it needs to be "configs/settings.properties" (not in "shared_configs", and it will need to overwrite the example settings.config).

**Comment by cmharlow** [comment]
also,  i can get wasapi-downloader cloned locally, built with gradle, settings used/setup, and the --help info showing, but can't get it to run with any actual downloads occurring (just following the "development" steps).
